add_library(matMul_acpp_lib STATIC Impl_AdaptiveCpp.h Impl_AdaptiveCpp.cpp Impl_AdaptiveCppShr.cpp Impl_AdaptiveCppShr.h)
target_compile_features(matMul_acpp_lib PUBLIC cxx_std_17)
if (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    target_link_libraries(matMul_acpp_lib PUBLIC ppb_sycl_offload)
else ()
    add_sycl_to_target(TARGET matMul_acpp_lib)
endif ()
target_link_libraries(matMul_acpp_lib PUBLIC matMul_lib)

add_executable(matMul_acpp main.cpp)
target_compile_features(matMul_acpp PUBLIC cxx_std_17)
target_link_libraries(matMul_acpp PUBLIC matMul_acpp_lib)
if (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    target_link_libraries(matMul_acpp PUBLIC ppb_sycl_offload)
else ()
    add_sycl_to_target(TARGET matMul_acpp)
endif ()