alpaka_add_library(nbody_alpaka_lib STATIC Impl_Alpaka.cpp Impl_Alpaka.h)
target_compile_features(nbody_alpaka_lib PUBLIC cxx_std_20)
target_link_libraries(nbody_alpaka_lib PUBLIC matMul_lib alpaka::alpaka)

alpaka_add_executable(nbody_alpaka main.cpp)
target_link_libraries(nbody_alpaka PUBLIC nbody_alpaka_lib)