# This environment can be used to compile AdaptiveCpp (v23.10.0) using the following command:
# cmake .. -G Ninja
#   -DCMAKE_PREFIX_PATH=$CONDA_PREFIX
#   -DLLVM_LIBRARY=$CONDA_PREFIX/lib/libLLVM.so
#   -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
#   -DCMAKE_C_COMPILER=$CONDA_PREFIX/bin/clang
#   -DCMAKE_CXX_COMPILER=$CONDA_PREFIX/bin/clang++
#   -DCMAKE_CUDA_COMPILER=$CONDA_PREFIX/bin/nvcc
# Build via and install `acpp` then into you conda environment
# Afterward, build your custom application via
# cmake .. -G Ninja
#   -DACPP_TARGETS="generic"
#   -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
# For running the SSCP "generic" application, you might need to add to you library path
# export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$CONDA_PREFIX/lib/hipSYCL/llvm-to-backend
name: ppb
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python==3.12
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - loguru
  - clang==15.0.7
  - clangxx==15.0.7
  - libclang==15.0.7
  - clangdev==15.0.7
  - llvm==15.0.7
  - llvm-openmp==15.0.7
  - llvm-tools==15.0.7
  - llvmdev==15.0.7
  - boost==1.85.0
  - spirv-tools
  - llvm-spirv=15.0.0
  - pocl
  - clinfo
  - cuda==12.6.0
  - cuda-opencl-dev
