add_library(matMul_cuda_lib STATIC Impl_Cuda.cu Impl_Cuda.cuh)
target_compile_features(matMul_cuda_lib PUBLIC cxx_std_17)
target_link_libraries(matMul_cuda_lib PUBLIC matMul_lib)
set_target_properties(matMul_cuda_lib PROPERTIES CUDA_SEPARABLE_COMPILATION ON)


add_executable(matMul_cuda main.cu)
target_link_libraries(matMul_cuda PRIVATE matMul_cuda_lib)
target_compile_features(matMul_cuda PUBLIC cxx_std_17)
set_target_properties(matMul_cuda PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
