add_library(nbody_acpp_lib STATIC Impl_AdaptiveCpp.h)
target_compile_features(nbody_acpp_lib PUBLIC cxx_std_20)
if (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    target_compile_options(nbody_acpp_lib PUBLIC -fsycl -fsycl-targets=nvptx64-nvidia-cuda)
    target_link_options(nbody_acpp_lib PUBLIC -fsycl -fsycl-targets=nvptx64-nvidia-cuda)
else ()
    add_sycl_to_target(TARGET nbody_acpp_lib)
endif ()
target_link_libraries(nbody_acpp_lib PUBLIC nbody_lib)

add_executable(nbody_acpp main.cpp)
target_compile_features(nbody_acpp PUBLIC cxx_std_20)
target_link_libraries(nbody_acpp PUBLIC nbody_acpp_lib)
if (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    target_compile_options(nbody_acpp PUBLIC -fsycl -fsycl-targets=nvptx64-nvidia-cuda)
    target_link_options(nbody_acpp PUBLIC -fsycl -fsycl-targets=nvptx64-nvidia-cuda)
else ()
    add_sycl_to_target(TARGET nbody_acpp)
endif ()

add_executable(param_search main_param_search.cpp)
target_compile_features(param_search PUBLIC cxx_std_20)
target_link_libraries(param_search PUBLIC nbody_acpp_lib)
if (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    target_compile_options(param_search PUBLIC -fsycl -fsycl-targets=nvptx64-nvidia-cuda)
    target_link_options(param_search PUBLIC -fsycl -fsycl-targets=nvptx64-nvidia-cuda)
else ()
    add_sycl_to_target(TARGET param_search)
endif ()