add_library(polyhedral_acpp_lib STATIC Impl_AdaptiveCpp.cpp)
target_compile_features(polyhedral_acpp_lib PUBLIC cxx_std_17)
if (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    target_link_libraries(polyhedral_acpp_lib PUBLIC ppb_sycl_offload)
else ()
    add_sycl_to_target(TARGET polyhedral_acpp_lib)
endif ()
target_link_libraries(polyhedral_acpp_lib PUBLIC polyhedral_lib)

add_executable(polyhedral_acpp ${POLYHEDRAL_GRAVITY_ROOT_DIR}/main.cpp)
target_compile_definitions(polyhedral_acpp PRIVATE PARADIGM="AdaptiveCpp")
target_compile_features(polyhedral_acpp PUBLIC cxx_std_17)
target_link_libraries(polyhedral_acpp PUBLIC polyhedral_acpp_lib)
if (CMAKE_CXX_COMPILER_ID STREQUAL "IntelLLVM")
    target_link_libraries(polyhedral_acpp PUBLIC ppb_sycl_offload)
else ()
    add_sycl_to_target(TARGET polyhedral_acpp)
endif ()
